app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_api:
  type: rest
  prefix: /api/postman
  resource: AppBundle\Controller\postmanController
  
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"