# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  authentication_handler:
    class: AppBundle\Handler\AuthenticationHandler
    arguments:  ["@router"]
    tags:
        - { name: 'monolog.logger', channel: 'security' }

  user_form.handler:
    class: AppBundle\Handler\UserFormHandler
    arguments: ['@service_container']